version: '3.8'

volumes:
  n8n_data:
services: 
  mcp-server:
    build:
      context: ./mcp-server
    container_name: mcp-server
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./mcp-server:/app
      - n8n_data:/app/logs
    command: ["python", "server.py"]
  
  # n8n
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=changeme
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=development
    volumes:
      - n8n_data:/home/node/.n8n